package com.neo.database.entities;
// Generated May 9, 2015 3:13:15 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AppProperty generated by hbm2java
 */
@Entity
@Table(name = "app_property", catalog = "project_ecommerce"
)
public class AppProperty implements java.io.Serializable {

    private Integer appPropertyId;
    private String property;
    private String propValue;

    public AppProperty() {
    }

    public AppProperty(String property, String propValue) {
        this.property = property;
        this.propValue = propValue;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "app_property_id", unique = true, nullable = false)
    public Integer getAppPropertyId() {
        return this.appPropertyId;
    }

    public void setAppPropertyId(Integer appPropertyId) {
        this.appPropertyId = appPropertyId;
    }

    @Column(name = "property", length = 45)
    public String getProperty() {
        return this.property;
    }

    public void setProperty(String property) {
        this.property = property;
    }

    @Column(name = "prop_value", length = 65535)
    public String getPropValue() {
        return this.propValue;
    }

    public void setPropValue(String propValue) {
        this.propValue = propValue;
    }

}
