package com.neo.database.entities;
// Generated May 9, 2015 3:13:15 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ContainerType generated by hbm2java
 */
@Entity
@Table(name = "container_type", catalog = "project_ecommerce"
)
public class ContainerType implements java.io.Serializable {

    private Integer containerTypeId;
    private String name;
    private Set<Container> containers = new HashSet<Container>(0);

    public ContainerType() {
    }

    public ContainerType(String name, Set<Container> containers) {
        this.name = name;
        this.containers = containers;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "container_type_id", unique = true, nullable = false)
    public Integer getContainerTypeId() {
        return this.containerTypeId;
    }

    public void setContainerTypeId(Integer containerTypeId) {
        this.containerTypeId = containerTypeId;
    }

    @Column(name = "name", length = 45)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "containerType")
    public Set<Container> getContainers() {
        return this.containers;
    }

    public void setContainers(Set<Container> containers) {
        this.containers = containers;
    }

}
