package com.neo.database.entities;
// Generated May 9, 2015 3:13:15 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CorouselImage generated by hbm2java
 */
@Entity
@Table(name = "corousel_image", catalog = "project_ecommerce"
)
public class CorouselImage implements java.io.Serializable {

    private Integer corouselImageId;
    private String name;
    private Byte ordinal;

    public CorouselImage() {
    }

    public CorouselImage(String name, Byte ordinal) {
        this.name = name;
        this.ordinal = ordinal;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "corousel_image_id", unique = true, nullable = false)
    public Integer getCorouselImageId() {
        return this.corouselImageId;
    }

    public void setCorouselImageId(Integer corouselImageId) {
        this.corouselImageId = corouselImageId;
    }

    @Column(name = "name", length = 45)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "ordinal")
    public Byte getOrdinal() {
        return this.ordinal;
    }

    public void setOrdinal(Byte ordinal) {
        this.ordinal = ordinal;
    }

}
