package com.neo.database.entities;
// Generated May 9, 2015 3:13:15 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DeliveryOption generated by hbm2java
 */
@Entity
@Table(name = "delivery_option", catalog = "project_ecommerce"
)
public class DeliveryOption implements java.io.Serializable {

    private Integer deliveryOptionId;
    private String name;
    private Set<ItemDeliveryOption> itemDeliveryOptions = new HashSet<ItemDeliveryOption>(0);

    public DeliveryOption() {
    }

    public DeliveryOption(String name, Set<ItemDeliveryOption> itemDeliveryOptions) {
        this.name = name;
        this.itemDeliveryOptions = itemDeliveryOptions;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "delivery_option_id", unique = true, nullable = false)
    public Integer getDeliveryOptionId() {
        return this.deliveryOptionId;
    }

    public void setDeliveryOptionId(Integer deliveryOptionId) {
        this.deliveryOptionId = deliveryOptionId;
    }

    @Column(name = "name", length = 100)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "deliveryOption")
    public Set<ItemDeliveryOption> getItemDeliveryOptions() {
        return this.itemDeliveryOptions;
    }

    public void setItemDeliveryOptions(Set<ItemDeliveryOption> itemDeliveryOptions) {
        this.itemDeliveryOptions = itemDeliveryOptions;
    }

}
