package com.neo.database.entities;
// Generated May 9, 2015 3:13:15 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * GuaranteeOption generated by hbm2java
 */
@Entity
@Table(name = "guarantee_option", catalog = "project_ecommerce"
)
public class GuaranteeOption implements java.io.Serializable {

    private Integer guaranteeOptionId;
    private String name;
    private Set<ItemGuaranteeOption> itemGuaranteeOptions = new HashSet<ItemGuaranteeOption>(0);

    public GuaranteeOption() {
    }

    public GuaranteeOption(String name, Set<ItemGuaranteeOption> itemGuaranteeOptions) {
        this.name = name;
        this.itemGuaranteeOptions = itemGuaranteeOptions;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "guarantee_option_id", unique = true, nullable = false)
    public Integer getGuaranteeOptionId() {
        return this.guaranteeOptionId;
    }

    public void setGuaranteeOptionId(Integer guaranteeOptionId) {
        this.guaranteeOptionId = guaranteeOptionId;
    }

    @Column(name = "name", length = 100)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "guaranteeOption")
    public Set<ItemGuaranteeOption> getItemGuaranteeOptions() {
        return this.itemGuaranteeOptions;
    }

    public void setItemGuaranteeOptions(Set<ItemGuaranteeOption> itemGuaranteeOptions) {
        this.itemGuaranteeOptions = itemGuaranteeOptions;
    }

}
