package com.neo.database.entities;
// Generated May 9, 2015 3:13:15 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ItemDeliveryOption generated by hbm2java
 */
@Entity
@Table(name = "item_delivery_option", catalog = "project_ecommerce"
)
public class ItemDeliveryOption implements java.io.Serializable {

    private Integer itemDeliveryOptionId;
    private DeliveryOption deliveryOption;
    private String description;
    private Set<Item> items = new HashSet<Item>(0);

    public ItemDeliveryOption() {
    }

    public ItemDeliveryOption(DeliveryOption deliveryOption) {
        this.deliveryOption = deliveryOption;
    }

    public ItemDeliveryOption(DeliveryOption deliveryOption, String description, Set<Item> items) {
        this.deliveryOption = deliveryOption;
        this.description = description;
        this.items = items;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "item_delivery_option_id", unique = true, nullable = false)
    public Integer getItemDeliveryOptionId() {
        return this.itemDeliveryOptionId;
    }

    public void setItemDeliveryOptionId(Integer itemDeliveryOptionId) {
        this.itemDeliveryOptionId = itemDeliveryOptionId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "delivery_option_id", nullable = false)
    public DeliveryOption getDeliveryOption() {
        return this.deliveryOption;
    }

    public void setDeliveryOption(DeliveryOption deliveryOption) {
        this.deliveryOption = deliveryOption;
    }

    @Column(name = "description")
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "itemDeliveryOption")
    public Set<Item> getItems() {
        return this.items;
    }

    public void setItems(Set<Item> items) {
        this.items = items;
    }

}
