package com.neo.database.entities;
// Generated May 9, 2015 3:13:15 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ItemCondition generated by hbm2java
 */
@Entity
@Table(name = "item_condition", catalog = "project_ecommerce"
)
public class ItemCondition implements java.io.Serializable {

    private Integer itemConditionId;
    private String name;
    private Set<Item> items = new HashSet<Item>(0);

    public ItemCondition() {
    }

    public ItemCondition(String name, Set<Item> items) {
        this.name = name;
        this.items = items;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "item_condition_id", unique = true, nullable = false)
    public Integer getItemConditionId() {
        return this.itemConditionId;
    }

    public void setItemConditionId(Integer itemConditionId) {
        this.itemConditionId = itemConditionId;
    }

    @Column(name = "name", length = 100)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "itemCondition")
    public Set<Item> getItems() {
        return this.items;
    }

    public void setItems(Set<Item> items) {
        this.items = items;
    }

}
