package com.neo.database.entities;
// Generated May 9, 2015 3:13:15 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ItemImage generated by hbm2java
 */
@Entity
@Table(name = "item_image", catalog = "project_ecommerce"
)
public class ItemImage implements java.io.Serializable {

    private Integer itemImageId;
    private Item item;
    private String name;
    private String caption;
    private Boolean defaultPic;

    public ItemImage() {
    }

    public ItemImage(Item item) {
        this.item = item;
    }

    public ItemImage(Item item, String name, String caption, Boolean defaultPic) {
        this.item = item;
        this.name = name;
        this.caption = caption;
        this.defaultPic = defaultPic;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "item_image_id", unique = true, nullable = false)
    public Integer getItemImageId() {
        return this.itemImageId;
    }

    public void setItemImageId(Integer itemImageId) {
        this.itemImageId = itemImageId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "item_id", nullable = false)
    public Item getItem() {
        return this.item;
    }

    public void setItem(Item item) {
        this.item = item;
    }

    @Column(name = "name", length = 45)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "caption", length = 45)
    public String getCaption() {
        return this.caption;
    }

    public void setCaption(String caption) {
        this.caption = caption;
    }

    @Column(name = "default_pic")
    public Boolean getDefaultPic() {
        return this.defaultPic;
    }

    public void setDefaultPic(Boolean defaultPic) {
        this.defaultPic = defaultPic;
    }

}
