package com.neo.database.entities;
// Generated May 9, 2015 3:13:15 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Item generated by hbm2java
 */
@Entity
@Table(name = "item", catalog = "project_ecommerce"
)
public class Item implements java.io.Serializable {

    private Integer itemId;
    private City city;
    private ItemCategory itemCategory;
    private ItemCondition itemCondition;
    private ItemDeliveryOption itemDeliveryOption;
    private ItemGuaranteeOption itemGuaranteeOption;
    private ItemReturnOption itemReturnOption;
    private String name;
    private String summary;
    private String description;
    private BigDecimal price;
    private BigDecimal priceOld;
    private String uid;
    private Long uidCreateTime;
    private Set<ContainerItem> containerItems = new HashSet<ContainerItem>(0);
    private Set<Review> reviews = new HashSet<Review>(0);
    private Set<ItemProperty> itemProperties = new HashSet<ItemProperty>(0);
    private Set<ItemImage> itemImages = new HashSet<ItemImage>(0);

    public Item() {
    }

    public Item(City city, ItemCategory itemCategory, ItemCondition itemCondition, ItemDeliveryOption itemDeliveryOption,
                ItemGuaranteeOption itemGuaranteeOption, ItemReturnOption itemReturnOption) {
        this.city = city;
        this.itemCategory = itemCategory;
        this.itemCondition = itemCondition;
        this.itemDeliveryOption = itemDeliveryOption;
        this.itemGuaranteeOption = itemGuaranteeOption;
        this.itemReturnOption = itemReturnOption;
    }

    public Item(City city, ItemCategory itemCategory, ItemCondition itemCondition, ItemDeliveryOption itemDeliveryOption,
                ItemGuaranteeOption itemGuaranteeOption, ItemReturnOption itemReturnOption, String name, String summary, String description,
                BigDecimal price, BigDecimal priceOld, String uid, Long uidCreateTime, Set<ContainerItem> containerItems,
                Set<Review> reviews, Set<ItemProperty> itemProperties, Set<ItemImage> itemImages) {
        this.city = city;
        this.itemCategory = itemCategory;
        this.itemCondition = itemCondition;
        this.itemDeliveryOption = itemDeliveryOption;
        this.itemGuaranteeOption = itemGuaranteeOption;
        this.itemReturnOption = itemReturnOption;
        this.name = name;
        this.summary = summary;
        this.description = description;
        this.price = price;
        this.priceOld = priceOld;
        this.uid = uid;
        this.uidCreateTime = uidCreateTime;
        this.containerItems = containerItems;
        this.reviews = reviews;
        this.itemProperties = itemProperties;
        this.itemImages = itemImages;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "item_id", unique = true, nullable = false)
    public Integer getItemId() {
        return this.itemId;
    }

    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "city_id", nullable = false)
    public City getCity() {
        return this.city;
    }

    public void setCity(City city) {
        this.city = city;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "item_category_id", nullable = false)
    public ItemCategory getItemCategory() {
        return this.itemCategory;
    }

    public void setItemCategory(ItemCategory itemCategory) {
        this.itemCategory = itemCategory;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "item_condition_id", nullable = false)
    public ItemCondition getItemCondition() {
        return this.itemCondition;
    }

    public void setItemCondition(ItemCondition itemCondition) {
        this.itemCondition = itemCondition;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "item_delivery_option_id", nullable = false)
    public ItemDeliveryOption getItemDeliveryOption() {
        return this.itemDeliveryOption;
    }

    public void setItemDeliveryOption(ItemDeliveryOption itemDeliveryOption) {
        this.itemDeliveryOption = itemDeliveryOption;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "item_guarantee_option_id", nullable = false)
    public ItemGuaranteeOption getItemGuaranteeOption() {
        return this.itemGuaranteeOption;
    }

    public void setItemGuaranteeOption(ItemGuaranteeOption itemGuaranteeOption) {
        this.itemGuaranteeOption = itemGuaranteeOption;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "item_return_option_id", nullable = false)
    public ItemReturnOption getItemReturnOption() {
        return this.itemReturnOption;
    }

    public void setItemReturnOption(ItemReturnOption itemReturnOption) {
        this.itemReturnOption = itemReturnOption;
    }

    @Column(name = "name", length = 100)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "summary")
    public String getSummary() {
        return this.summary;
    }

    public void setSummary(String summary) {
        this.summary = summary;
    }

    @Column(name = "description", length = 65535)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "price", precision = 10)
    public BigDecimal getPrice() {
        return this.price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    @Column(name = "price_old", precision = 10)
    public BigDecimal getPriceOld() {
        return this.priceOld;
    }

    public void setPriceOld(BigDecimal priceOld) {
        this.priceOld = priceOld;
    }

    @Column(name = "uid", length = 45)
    public String getUid() {
        return this.uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    @Column(name = "uid_create_time")
    public Long getUidCreateTime() {
        return this.uidCreateTime;
    }

    public void setUidCreateTime(Long uidCreateTime) {
        this.uidCreateTime = uidCreateTime;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "item")
    public Set<ContainerItem> getContainerItems() {
        return this.containerItems;
    }

    public void setContainerItems(Set<ContainerItem> containerItems) {
        this.containerItems = containerItems;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "item")
    public Set<Review> getReviews() {
        return this.reviews;
    }

    public void setReviews(Set<Review> reviews) {
        this.reviews = reviews;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "item")
    public Set<ItemProperty> getItemProperties() {
        return this.itemProperties;
    }

    public void setItemProperties(Set<ItemProperty> itemProperties) {
        this.itemProperties = itemProperties;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "item")
    public Set<ItemImage> getItemImages() {
        return this.itemImages;
    }

    public void setItemImages(Set<ItemImage> itemImages) {
        this.itemImages = itemImages;
    }

}
