package com.neo.database.entities;
// Generated May 9, 2015 3:13:15 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ItemGuaranteeOption generated by hbm2java
 */
@Entity
@Table(name = "item_guarantee_option", catalog = "project_ecommerce"
)
public class ItemGuaranteeOption implements java.io.Serializable {

    private Integer itemGuaranteeOptionId;
    private GuaranteeOption guaranteeOption;
    private String description;
    private String timeLimit;
    private Set<Item> items = new HashSet<Item>(0);

    public ItemGuaranteeOption() {
    }

    public ItemGuaranteeOption(GuaranteeOption guaranteeOption) {
        this.guaranteeOption = guaranteeOption;
    }

    public ItemGuaranteeOption(GuaranteeOption guaranteeOption, String description, String timeLimit, Set<Item> items) {
        this.guaranteeOption = guaranteeOption;
        this.description = description;
        this.timeLimit = timeLimit;
        this.items = items;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "item_guarantee_option_id", unique = true, nullable = false)
    public Integer getItemGuaranteeOptionId() {
        return this.itemGuaranteeOptionId;
    }

    public void setItemGuaranteeOptionId(Integer itemGuaranteeOptionId) {
        this.itemGuaranteeOptionId = itemGuaranteeOptionId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "guarantee_option_id", nullable = false)
    public GuaranteeOption getGuaranteeOption() {
        return this.guaranteeOption;
    }

    public void setGuaranteeOption(GuaranteeOption guaranteeOption) {
        this.guaranteeOption = guaranteeOption;
    }

    @Column(name = "description")
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "time_limit", length = 45)
    public String getTimeLimit() {
        return this.timeLimit;
    }

    public void setTimeLimit(String timeLimit) {
        this.timeLimit = timeLimit;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "itemGuaranteeOption")
    public Set<Item> getItems() {
        return this.items;
    }

    public void setItems(Set<Item> items) {
        this.items = items;
    }

}
