package com.neo.database.entities;
// Generated May 9, 2015 3:13:15 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ItemProperty generated by hbm2java
 */
@Entity
@Table(name = "item_property", catalog = "project_ecommerce"
)
public class ItemProperty implements java.io.Serializable {

    private Integer itemPropertyId;
    private Item item;
    private Property property;
    private String value;
    private Boolean visible;

    public ItemProperty() {
    }

    public ItemProperty(Item item, Property property) {
        this.item = item;
        this.property = property;
    }

    public ItemProperty(Item item, Property property, String value, Boolean visible) {
        this.item = item;
        this.property = property;
        this.value = value;
        this.visible = visible;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "item_property_id", unique = true, nullable = false)
    public Integer getItemPropertyId() {
        return this.itemPropertyId;
    }

    public void setItemPropertyId(Integer itemPropertyId) {
        this.itemPropertyId = itemPropertyId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "item_id", nullable = false)
    public Item getItem() {
        return this.item;
    }

    public void setItem(Item item) {
        this.item = item;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "property_id", nullable = false)
    public Property getProperty() {
        return this.property;
    }

    public void setProperty(Property property) {
        this.property = property;
    }

    @Column(name = "value")
    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    @Column(name = "visible")
    public Boolean getVisible() {
        return this.visible;
    }

    public void setVisible(Boolean visible) {
        this.visible = visible;
    }

}
