package com.neo.database.entities;
// Generated May 9, 2015 3:13:15 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MessageSubject generated by hbm2java
 */
@Entity
@Table(name = "message_subject", catalog = "project_ecommerce"
)
public class MessageSubject implements java.io.Serializable {

    private Integer messageSubjectId;
    private String name;
    private String type;
    private Set<Message> messages = new HashSet<Message>(0);

    public MessageSubject() {
    }

    public MessageSubject(String name, String type, Set<Message> messages) {
        this.name = name;
        this.type = type;
        this.messages = messages;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "message_subject_id", unique = true, nullable = false)
    public Integer getMessageSubjectId() {
        return this.messageSubjectId;
    }

    public void setMessageSubjectId(Integer messageSubjectId) {
        this.messageSubjectId = messageSubjectId;
    }

    @Column(name = "name", length = 100)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "type", length = 45)
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "messageSubject")
    public Set<Message> getMessages() {
        return this.messages;
    }

    public void setMessages(Set<Message> messages) {
        this.messages = messages;
    }

}
