package com.neo.database.entities;
// Generated May 9, 2015 3:13:15 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name = "message", catalog = "project_ecommerce"
)
public class Message implements java.io.Serializable {

    private Integer messageId;
    private ContainerItem containerItem;
    private MessageSubject messageSubject;
    private User userByUserTo;
    private User userByUserFrom;
    private String text;
    private Long sentTime;
    private Long receivedTime;

    public Message() {
    }

    public Message(MessageSubject messageSubject, User userByUserTo, User userByUserFrom) {
        this.messageSubject = messageSubject;
        this.userByUserTo = userByUserTo;
        this.userByUserFrom = userByUserFrom;
    }

    public Message(ContainerItem containerItem, MessageSubject messageSubject, User userByUserTo, User userByUserFrom, String text,
                   Long sentTime, Long receivedTime) {
        this.containerItem = containerItem;
        this.messageSubject = messageSubject;
        this.userByUserTo = userByUserTo;
        this.userByUserFrom = userByUserFrom;
        this.text = text;
        this.sentTime = sentTime;
        this.receivedTime = receivedTime;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "message_id", unique = true, nullable = false)
    public Integer getMessageId() {
        return this.messageId;
    }

    public void setMessageId(Integer messageId) {
        this.messageId = messageId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "reference_item_id")
    public ContainerItem getContainerItem() {
        return this.containerItem;
    }

    public void setContainerItem(ContainerItem containerItem) {
        this.containerItem = containerItem;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "message_subject_id", nullable = false)
    public MessageSubject getMessageSubject() {
        return this.messageSubject;
    }

    public void setMessageSubject(MessageSubject messageSubject) {
        this.messageSubject = messageSubject;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_to", nullable = false)
    public User getUserByUserTo() {
        return this.userByUserTo;
    }

    public void setUserByUserTo(User userByUserTo) {
        this.userByUserTo = userByUserTo;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_from", nullable = false)
    public User getUserByUserFrom() {
        return this.userByUserFrom;
    }

    public void setUserByUserFrom(User userByUserFrom) {
        this.userByUserFrom = userByUserFrom;
    }

    @Column(name = "text", length = 65535)
    public String getText() {
        return this.text;
    }

    public void setText(String text) {
        this.text = text;
    }

    @Column(name = "sent_time")
    public Long getSentTime() {
        return this.sentTime;
    }

    public void setSentTime(Long sentTime) {
        this.sentTime = sentTime;
    }

    @Column(name = "received_time")
    public Long getReceivedTime() {
        return this.receivedTime;
    }

    public void setReceivedTime(Long receivedTime) {
        this.receivedTime = receivedTime;
    }

}
