package com.neo.database.entities;
// Generated May 9, 2015 3:13:15 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Property generated by hbm2java
 */
@Entity
@Table(name = "property", catalog = "project_ecommerce"
)
public class Property implements java.io.Serializable {

    private Integer propertyId;
    private String name;
    private Boolean defaultProp;
    private Set<ItemProperty> itemProperties = new HashSet<ItemProperty>(0);

    public Property() {
    }

    public Property(String name, Boolean defaultProp, Set<ItemProperty> itemProperties) {
        this.name = name;
        this.defaultProp = defaultProp;
        this.itemProperties = itemProperties;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "property_id", unique = true, nullable = false)
    public Integer getPropertyId() {
        return this.propertyId;
    }

    public void setPropertyId(Integer propertyId) {
        this.propertyId = propertyId;
    }

    @Column(name = "name", length = 45)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "default_prop")
    public Boolean getDefaultProp() {
        return this.defaultProp;
    }

    public void setDefaultProp(Boolean defaultProp) {
        this.defaultProp = defaultProp;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "property")
    public Set<ItemProperty> getItemProperties() {
        return this.itemProperties;
    }

    public void setItemProperties(Set<ItemProperty> itemProperties) {
        this.itemProperties = itemProperties;
    }

}
