package com.neo.database.entities;
// Generated Mar 14, 2015 6:04:53 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserConst generated by hbm2java
 */
@Entity
@Table(name = "sale", catalog = "project_ecommerce"
)
public class Sale implements java.io.Serializable {

    private User buyer;
    private Item item;
    private Long soldTime;
    private Integer quantity;
    private BigDecimal unitPrice;
    private BigDecimal commission;

    public Sale() {
    }

    public Sale(User buyer, Item item, long soldTime, int quantity, BigDecimal commission) {
        this.buyer = buyer;
        this.item = item;
        this.soldTime = soldTime;
        this.quantity = quantity;
        this.commission = commission;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "buyer_id", nullable = false)
    public User getBuyer() {
        return buyer;
    }

    public void setBuyer(User buyer) {
        this.buyer = buyer;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "item_id", nullable = false)
    public Item getItem() {
        return item;
    }

    public void setItem(Item item) {
        this.item = item;
    }

    @Column(name = "commission", nullable = false)
    public BigDecimal getCommission() {
        return commission;
    }

    public void setCommission(BigDecimal commission) {
        this.commission = commission;
    }

    @Column(name = "sold_time", nullable = false)
    @Id
    public Long getSoldTime() {
        return soldTime;
    }

    public void setSoldTime(Long soldTime) {
        this.soldTime = soldTime;
    }

    @Column(name = "quantity", nullable = false)
    public Integer getQuantity() {
        return quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    @Column(name = "unit_price", nullable = false)
    public BigDecimal getUnitPrice() {
        return unitPrice;
    }

    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }
}
