package com.neo.database.entities;
// Generated May 9, 2015 3:13:15 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SecurityQuestion generated by hbm2java
 */
@Entity
@Table(name = "security_question", catalog = "project_ecommerce"
)
public class SecurityQuestion implements java.io.Serializable {

    private Integer securityQuestionId;
    private String question;
    private Set<UserSecurityQuestion> userSecurityQuestions = new HashSet<UserSecurityQuestion>(0);

    public SecurityQuestion() {
    }

    public SecurityQuestion(String question, Set<UserSecurityQuestion> userSecurityQuestions) {
        this.question = question;
        this.userSecurityQuestions = userSecurityQuestions;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "security_question_id", unique = true, nullable = false)
    public Integer getSecurityQuestionId() {
        return this.securityQuestionId;
    }

    public void setSecurityQuestionId(Integer securityQuestionId) {
        this.securityQuestionId = securityQuestionId;
    }

    @Column(name = "question", length = 100)
    public String getQuestion() {
        return this.question;
    }

    public void setQuestion(String question) {
        this.question = question;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "securityQuestion")
    public Set<UserSecurityQuestion> getUserSecurityQuestions() {
        return this.userSecurityQuestions;
    }

    public void setUserSecurityQuestions(Set<UserSecurityQuestion> userSecurityQuestions) {
        this.userSecurityQuestions = userSecurityQuestions;
    }

}
