package com.neo.database.entities;
// Generated Mar 14, 2015 6:04:53 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserConst generated by hbm2java
 */
@Entity
@Table(name = "user_const", catalog = "project_ecommerce"
)
public class UserConst implements java.io.Serializable {

    private String email;
    private String username;

    public UserConst() {
    }

    public UserConst(String email) {
        this.email = email;
    }

    public UserConst(String email, String username) {
        this.email = email;
        this.username = username;
    }

    @Id
    @Column(name = "email", nullable = false)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "username", nullable = false)
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

}
