package com.neo.database.entities;
// Generated May 9, 2015 3:13:15 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserPermission generated by hbm2java
 */
@Entity
@Table(name = "user_permission", catalog = "project_ecommerce"
)
public class UserPermission implements java.io.Serializable {

    private Integer userPermissionId;
    private Permission permission;
    private UserType userType;
    private Boolean allowed;

    public UserPermission() {
    }

    public UserPermission(Permission permission, UserType userType) {
        this.permission = permission;
        this.userType = userType;
    }

    public UserPermission(Permission permission, UserType userType, Boolean allowed) {
        this.permission = permission;
        this.userType = userType;
        this.allowed = allowed;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "user_permission_id", unique = true, nullable = false)
    public Integer getUserPermissionId() {
        return this.userPermissionId;
    }

    public void setUserPermissionId(Integer userPermissionId) {
        this.userPermissionId = userPermissionId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "permission_id", nullable = false)
    public Permission getPermission() {
        return this.permission;
    }

    public void setPermission(Permission permission) {
        this.permission = permission;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_type_id", nullable = false)
    public UserType getUserType() {
        return this.userType;
    }

    public void setUserType(UserType userType) {
        this.userType = userType;
    }

    @Column(name = "allowed")
    public Boolean getAllowed() {
        return this.allowed;
    }

    public void setAllowed(Boolean allowed) {
        this.allowed = allowed;
    }

}
